from __future__ import annotations

from typing import Any


def hero_apk_profile() -> dict[str, Any]:
    """Explicit synthetic fixture. It is never used as an error fallback."""
    return {
        "schema_version": "3.0",
        "extractor_version": "demo-fixture-2026.4",
        "analysis_mode": "static",
        "analysis_quality": "synthetic",
        "engine": "explicit-demo-fixture",
        "warnings": ["Synthetic demonstration evidence; not derived from a submitted APK."],
        "file": {
            "name": "BOI-Rewards-DEMO.apk",
            "size_bytes": 1048576,
            "sha256": "0" * 64,
            "archive_entry_count": 42,
            "dex_files": ["classes.dex"],
            "native_library_count": 0,
            "embedded_payloads": ["assets/update.dex"],
        },
        "app": {
            "package_name": "com.fraudshield.demo.fakebank",
            "app_label": "Bank of India Mobile Rewards",
            "version_name": "2.4.1-demo",
            "version_code": "241",
            "min_sdk": "24",
            "target_sdk": "35",
        },
        "permissions": {
            "requested": [
                "android.permission.INTERNET",
                "android.permission.READ_SMS",
                "android.permission.RECEIVE_SMS",
                "android.permission.SYSTEM_ALERT_WINDOW",
                "android.permission.REQUEST_INSTALL_PACKAGES",
                "android.permission.QUERY_ALL_PACKAGES",
            ],
            "flagged_dangerous": [
                "android.permission.READ_SMS",
                "android.permission.RECEIVE_SMS",
                "android.permission.SYSTEM_ALERT_WINDOW",
                "android.permission.REQUEST_INSTALL_PACKAGES",
                "android.permission.QUERY_ALL_PACKAGES",
            ],
        },
        "components": {
            "activities": ["com.fraudshield.demo.fakebank.MainActivity"],
            "services": ["com.fraudshield.demo.fakebank.CaptureService"],
            "receivers": ["com.fraudshield.demo.fakebank.SmsReceiver"],
            "providers": [],
            "exported": [{"type": "receiver", "name": "com.fraudshield.demo.fakebank.SmsReceiver"}],
            "sms_receiver": True,
            "boot_receiver": True,
            "accessibility_service": True,
        },
        "certificate": {
            "issuer": "CN=FraudShield Demo Debug",
            "subject": "CN=FraudShield Demo Debug",
            "is_self_signed": True,
            "sha256": "1" * 64,
            "signature_entries": [],
            "trust_evaluation": "not_in_trusted_inventory",
            "bank_impersonation_flag": True,
        },
        "network_indicators": {
            "urls": [
                "https://c2-demo.fraudshield.invalid/gate",
                "https://boi-kyc-demo-2026.firebaseio.com/stolen_otps.json",
                "https://boi-kyc-demo-2026.appspot.com/payload.dex",
            ],
            "domains": ["c2-demo.fraudshield.invalid", "boi-kyc-demo-2026.firebaseio.com"],
            "ips": ["198.51.100.42"],
        },
        "code_signals": {
            "dynamic_code_loading": {"detected": True, "evidence": ["DexClassLoader", "InMemoryDexClassLoader"]},
            "reflection": {"detected": True, "evidence": ["java/lang/reflect"]},
            "sms_api": {"detected": True, "evidence": ["SmsManager", "onReceive"]},
            "installed_app_enumeration": {"detected": True, "evidence": ["getInstalledApplications"]},
            "crypto_api": {"detected": True, "evidence": ["javax/crypto/Cipher"]},
            "command_execution": {"detected": False, "evidence": []},
            "accessibility_api": {"detected": True, "evidence": ["AccessibilityService", "onAccessibilityEvent"]},
            "input_injection": {"detected": True, "evidence": ["dispatchGesture"]},
            "credential_theft": {"detected": True, "evidence": ["Password", "MPIN", "CardNumber"]},
            "phishing_indicators": {"detected": True, "evidence": ["NetBanking Login Overlay"]},
            "webview_bridge": {"detected": False, "evidence": []},
            "device_admin": {"detected": False, "evidence": []},
        },
        "obfuscation": {
            "class_count_observed": 120,
            "short_class_count": 65,
            "short_class_ratio": 0.5417,
            "base64_blob_count": 3,
            "likely_name_obfuscation": True,
        },
        "coverage": {"archive": True, "manifest": True, "dex": True, "certificate": True, "dynamic": True},
        "icon_phash": "1111222233334444",
        "method_level_evidence": [
            {
                "signature_id": "MTH-SMS-001",
                "title": "SMS Message Interception Handler",
                "category": "SMS_INTERCEPTION",
                "class_name": "com.fraudshield.demo.fakebank.SmsReceiver",
                "method_name": "onReceive",
                "confidence": 0.95,
            },
            {
                "signature_id": "MTH-DYN-001",
                "title": "In-Memory Secondary DEX Execution",
                "category": "DYNAMIC_CODE_LOADING",
                "class_name": "com.fraudshield.demo.fakebank.Loader",
                "method_name": "loadDynamicDEX",
                "confidence": 0.90,
            },
        ],
        "recovered_payloads": [
            {
                "payload_id": "PAYLOAD-001",
                "parent_sample_sha256": "0" * 64,
                "sha256": "2" * 64,
                "payload_type": "DEX",
                "size_bytes": 48200,
                "source": "MEMORY_DUMP",
                "loader": "dalvik.system.InMemoryDexClassLoader",
                "storage_reference": "runtime/recovered_payloads/PAYLOAD-001.dex",
                "analysis_status": "ANALYZED",
                "extracted_capabilities": ["SMS_INTERCEPTION", "ACCESSIBILITY_AUTOMATION"],
                "method_level_evidence": [
                    {
                        "signature_id": "MTH-SMS-002",
                        "title": "Automated OTP Forwarder",
                        "class_name": "com.payload.HiddenForwarder",
                        "method_name": "forwardSecret",
                        "confidence": 0.94,
                    }
                ],
            }
        ],
        "runtime_evidence": [
            {
                "evidence_id": "RE-001",
                "timestamp_ms": 1718000001000,
                "event_type": "sms_received_broadcast",
                "trust_level": "INSTRUMENTED",
                "description": "Android SMS broadcast delivered with OTP marker DS-TEST-OTP-749231",
                "source": "FRIDA_OBSERVER",
                "api": "android.content.BroadcastReceiver.onReceive(Context, Intent)",
                "arguments": ["pdus_data", "DS-TEST-OTP-749231"],
                "return_value": None,
                "process": 4120,
            },
            {
                "evidence_id": "RE-002",
                "timestamp_ms": 1718000002500,
                "event_type": "http_request",
                "trust_level": "PAYLOAD_CORRELATED",
                "description": "Outbound HTTP POST containing synthetic marker DS-TEST-OTP-749231 exfiltrated to Firebase endpoint",
                "source": "FRIDA_OBSERVER",
                "api": "com.android.okhttp.internal.http.HttpEngine.sendRequest()",
                "arguments": ["https://boi-kyc-demo-2026.firebaseio.com/stolen_otps.json", "{\"otp\":\"DS-TEST-OTP-749231\"}"],
                "return_value": "200 OK",
                "process": 4120,
            },
            {
                "evidence_id": "RE-003",
                "timestamp_ms": 1718000003000,
                "event_type": "dynamic_dex_loaded",
                "trust_level": "INSTRUMENTED",
                "description": "InMemoryDexClassLoader invoked to execute secondary dynamic bytecode",
                "source": "FRIDA_OBSERVER",
                "api": "dalvik.system.InMemoryDexClassLoader.<init>(ByteBuffer, ClassLoader)",
                "arguments": ["ByteBuffer[size=48200]"],
                "return_value": None,
                "process": 4120,
            },
        ],
        "dynamic_experiment_results": [
            {
                "experiment_id": "EXP-001",
                "experiment_type": "SMS_INTERCEPTION_OBSERVATION",
                "status": "COMPLETED",
                "hypothesis_id": "H1",
                "generated_evidence_ids": ["RE-001", "RE-002"],
                "execution_log": "Synthetic OTP marker successfully injected and intercepted",
            },
            {
                "experiment_id": "EXP-002",
                "experiment_type": "DYNAMIC_CODE_LOAD_OBSERVATION",
                "status": "COMPLETED",
                "hypothesis_id": "H2",
                "generated_evidence_ids": ["RE-003"],
                "execution_log": "Dynamic in-memory DEX load observed and artifact recovered as PAYLOAD-001",
            },
        ],
    }
