{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fraudshield.fullname" . }}
  labels:
    {{- include "fraudshield.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "fraudshield.fullname" . }}
                port:
                  name: http
          - path: /health
            pathType: Exact
            backend:
              service:
                name: {{ include "fraudshield.fullname" . }}
                port:
                  name: http
          {{- if .Values.frontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fraudshield.fullname" . }}-frontend
                port:
                  name: http
          {{- end }}
{{- end }}
